### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by bg-zhangqihao** [jphastings/TescoGroceries#1]
Hello, this website https://secure.techfortesco.com/tescoapiweb/ cannot be opened, is there any solution? I want to use this Tesco Groceries API

**Comment by jphastings** [comment]
I'm afraid I'm not sure! I built this library _many_ years ago, and it's fallen into disrepair. I'm currently travelling and away from my computer, so I won't be able to investigate for a long time.

Good luck, I'll let you know if I do address this when I get home in May!

**Comment by bg-zhangqihao** [comment]
> 

I'll look for a solution before that, thank you very much!

**Comment by safwatmohamed** [comment]
@bg-zhangqihao Hello, did you find a soultion? I think Tesco removed public acess to their api

**Comment by jphastings** [comment]
Yeah, that domain is now owned by someone else; the API this library used no longer exists (anywhere that I can find) — I'll post a note and archive this repo.

Sorry folks!
